password:
    resource: "@QuickPasswordBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@PasswordBundle/Controller/"
    type:     annotation

Memorable:
    resource: "@PasswordBundle/Controller/"
    type:     annotation